// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_1d2_HH_
#define _dct_1d2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_mul_mul_16s_1jbC.h"
#include "dct_mac_muladd_16kbM.h"
#include "dct_mac_muladd_16lbW.h"
#include "dct_mac_muladd_16mb6.h"
#include "dct_1d2_dct_coeffbkb.h"
#include "dct_1d2_dct_coeffcud.h"
#include "dct_1d2_dct_coeffdEe.h"
#include "dct_1d2_dct_coeffeOg.h"
#include "dct_1d2_dct_coefffYi.h"
#include "dct_1d2_dct_coeffg8j.h"
#include "dct_1d2_dct_coeffhbi.h"
#include "dct_1d2_dct_coeffibs.h"

namespace ap_rtl {

struct dct_1d2 : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > src_address0;
    sc_out< sc_logic > src_ce0;
    sc_in< sc_lv<16> > src_q0;
    sc_out< sc_lv<6> > src_address1;
    sc_out< sc_logic > src_ce1;
    sc_in< sc_lv<16> > src_q1;
    sc_in< sc_lv<4> > src_offset;
    sc_out< sc_lv<6> > dst_address0;
    sc_out< sc_logic > dst_ce0;
    sc_out< sc_logic > dst_we0;
    sc_out< sc_lv<16> > dst_d0;
    sc_in< sc_lv<4> > dst_offset;


    // Module declarations
    dct_1d2(sc_module_name name);
    SC_HAS_PROCESS(dct_1d2);

    ~dct_1d2();

    sc_trace_file* mVcdFile;

    dct_1d2_dct_coeffbkb* dct_coeff_table_0_U;
    dct_1d2_dct_coeffcud* dct_coeff_table_1_U;
    dct_1d2_dct_coeffdEe* dct_coeff_table_2_U;
    dct_1d2_dct_coeffeOg* dct_coeff_table_3_U;
    dct_1d2_dct_coefffYi* dct_coeff_table_4_U;
    dct_1d2_dct_coeffg8j* dct_coeff_table_5_U;
    dct_1d2_dct_coeffhbi* dct_coeff_table_6_U;
    dct_1d2_dct_coeffibs* dct_coeff_table_7_U;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U1;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U2;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U3;
    dct_mac_muladd_16kbM<1,1,16,15,14,29>* dct_mac_muladd_16kbM_U4;
    dct_mac_muladd_16lbW<1,1,16,14,29,29>* dct_mac_muladd_16lbW_U5;
    dct_mac_muladd_16mb6<1,1,16,15,29,29>* dct_mac_muladd_16mb6_U6;
    dct_mac_muladd_16mb6<1,1,16,15,29,29>* dct_mac_muladd_16mb6_U7;
    dct_mac_muladd_16mb6<1,1,16,15,29,29>* dct_mac_muladd_16mb6_U8;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > dct_coeff_table_0_address0;
    sc_signal< sc_logic > dct_coeff_table_0_ce0;
    sc_signal< sc_lv<14> > dct_coeff_table_0_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_1_address0;
    sc_signal< sc_logic > dct_coeff_table_1_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_1_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_2_address0;
    sc_signal< sc_logic > dct_coeff_table_2_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_2_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_3_address0;
    sc_signal< sc_logic > dct_coeff_table_3_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_3_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_4_address0;
    sc_signal< sc_logic > dct_coeff_table_4_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_4_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_5_address0;
    sc_signal< sc_logic > dct_coeff_table_5_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_5_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_6_address0;
    sc_signal< sc_logic > dct_coeff_table_6_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_6_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_7_address0;
    sc_signal< sc_logic > dct_coeff_table_7_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_7_q0;
    sc_signal< sc_lv<4> > k_0_reg_280;
    sc_signal< sc_lv<16> > reg_291;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage1_iter0;
    sc_signal< bool > ap_block_state7_pp0_stage1_iter1;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<1> > icmp_ln11_reg_644;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage2;
    sc_signal< bool > ap_block_state4_pp0_stage2_iter0;
    sc_signal< bool > ap_block_state8_pp0_stage2_iter1;
    sc_signal< bool > ap_block_pp0_stage2_11001;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage3;
    sc_signal< bool > ap_block_state5_pp0_stage3_iter0;
    sc_signal< bool > ap_block_state9_pp0_stage3_iter1;
    sc_signal< bool > ap_block_pp0_stage3_11001;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > reg_295;
    sc_signal< sc_lv<8> > zext_ln17_2_fu_307_p1;
    sc_signal< sc_lv<8> > zext_ln17_2_reg_599;
    sc_signal< sc_lv<6> > src_addr_reg_604;
    sc_signal< sc_lv<6> > src_addr_1_reg_609;
    sc_signal< sc_lv<6> > src_addr_2_reg_614;
    sc_signal< sc_lv<6> > src_addr_3_reg_619;
    sc_signal< sc_lv<6> > src_addr_4_reg_624;
    sc_signal< sc_lv<6> > src_addr_5_reg_629;
    sc_signal< sc_lv<6> > src_addr_6_reg_634;
    sc_signal< sc_lv<6> > src_addr_7_reg_639;
    sc_signal< sc_lv<1> > icmp_ln11_fu_429_p2;
    sc_signal< sc_lv<1> > icmp_ln11_reg_644_pp0_iter1_reg;
    sc_signal< sc_lv<4> > k_fu_435_p2;
    sc_signal< sc_lv<4> > k_reg_648;
    sc_signal< sc_lv<8> > add_ln19_8_fu_457_p2;
    sc_signal< sc_lv<8> > add_ln19_8_reg_653;
    sc_signal< sc_lv<8> > add_ln19_8_reg_653_pp0_iter1_reg;
    sc_signal< sc_lv<14> > dct_coeff_table_0_lo_reg_698;
    sc_signal< sc_lv<15> > dct_coeff_table_1_lo_reg_703;
    sc_signal< sc_lv<15> > dct_coeff_table_2_lo_reg_708;
    sc_signal< sc_lv<15> > dct_coeff_table_3_lo_reg_713;
    sc_signal< sc_lv<15> > dct_coeff_table_4_lo_reg_718;
    sc_signal< sc_lv<15> > dct_coeff_table_5_lo_reg_723;
    sc_signal< sc_lv<15> > dct_coeff_table_6_lo_reg_728;
    sc_signal< sc_lv<15> > dct_coeff_table_7_lo_reg_733;
    sc_signal< sc_lv<29> > mul_ln17_1_fu_545_p2;
    sc_signal< sc_lv<29> > mul_ln17_1_reg_738;
    sc_signal< sc_lv<29> > mul_ln17_3_fu_551_p2;
    sc_signal< sc_lv<29> > mul_ln17_3_reg_743;
    sc_signal< sc_lv<29> > mul_ln17_5_fu_557_p2;
    sc_signal< sc_lv<29> > mul_ln17_5_reg_748;
    sc_signal< sc_lv<29> > grp_fu_563_p3;
    sc_signal< sc_lv<29> > add_ln19_5_reg_753;
    sc_signal< sc_lv<29> > grp_fu_571_p3;
    sc_signal< sc_lv<29> > add_ln19_1_reg_758;
    sc_signal< sc_lv<29> > grp_fu_578_p3;
    sc_signal< sc_lv<29> > add_ln19_2_reg_763;
    sc_signal< sc_lv<29> > add_ln19_3_fu_518_p2;
    sc_signal< sc_lv<29> > add_ln19_3_reg_768;
    sc_signal< sc_lv<29> > grp_fu_585_p3;
    sc_signal< sc_lv<29> > add_ln19_4_reg_773;
    sc_signal< sc_lv<29> > grp_fu_592_p3;
    sc_signal< sc_lv<29> > add_ln19_6_reg_778;
    sc_signal< sc_lv<16> > trunc_ln_reg_783;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< bool > ap_block_pp0_stage3_subdone;
    sc_signal< sc_lv<4> > ap_phi_mux_k_0_phi_fu_284_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<64> > zext_ln17_1_fu_319_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_330_p3;
    sc_signal< sc_lv<64> > tmp_7_fu_345_p3;
    sc_signal< sc_lv<64> > tmp_8_fu_360_p3;
    sc_signal< sc_lv<64> > tmp_9_fu_375_p3;
    sc_signal< sc_lv<64> > tmp_s_fu_390_p3;
    sc_signal< sc_lv<64> > tmp_1_fu_405_p3;
    sc_signal< sc_lv<64> > tmp_2_fu_420_p3;
    sc_signal< sc_lv<64> > zext_ln16_fu_441_p1;
    sc_signal< sc_lv<64> > zext_ln19_1_fu_541_p1;
    sc_signal< bool > ap_block_pp0_stage3;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< bool > ap_block_pp0_stage2;
    sc_signal< sc_lv<7> > tmp_4_fu_299_p3;
    sc_signal< sc_lv<7> > tmp_5_fu_311_p3;
    sc_signal< sc_lv<7> > or_ln17_fu_324_p2;
    sc_signal< sc_lv<7> > or_ln17_1_fu_339_p2;
    sc_signal< sc_lv<7> > or_ln17_2_fu_354_p2;
    sc_signal< sc_lv<7> > or_ln17_3_fu_369_p2;
    sc_signal< sc_lv<7> > or_ln17_4_fu_384_p2;
    sc_signal< sc_lv<7> > or_ln17_5_fu_399_p2;
    sc_signal< sc_lv<7> > or_ln17_6_fu_414_p2;
    sc_signal< sc_lv<8> > zext_ln19_fu_453_p1;
    sc_signal< sc_lv<29> > add_ln19_7_fu_522_p2;
    sc_signal< sc_lv<29> > add_ln19_fu_526_p2;
    sc_signal< sc_lv<14> > grp_fu_563_p2;
    sc_signal< sc_lv<14> > grp_fu_571_p1;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< bool > ap_block_pp0_stage2_subdone;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<29> > grp_fu_571_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage0;
    static const sc_lv<6> ap_ST_fsm_pp0_stage1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage2;
    static const sc_lv<6> ap_ST_fsm_pp0_stage3;
    static const sc_lv<6> ap_ST_fsm_state10;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<57> ap_const_lv57_0;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<7> ap_const_lv7_3;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<7> ap_const_lv7_5;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<29> ap_const_lv29_1000;
    static const sc_lv<32> ap_const_lv32_5;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln19_3_fu_518_p2();
    void thread_add_ln19_7_fu_522_p2();
    void thread_add_ln19_8_fu_457_p2();
    void thread_add_ln19_fu_526_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_pp0_stage2();
    void thread_ap_block_pp0_stage2_11001();
    void thread_ap_block_pp0_stage2_subdone();
    void thread_ap_block_pp0_stage3();
    void thread_ap_block_pp0_stage3_11001();
    void thread_ap_block_pp0_stage3_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage1_iter0();
    void thread_ap_block_state4_pp0_stage2_iter0();
    void thread_ap_block_state5_pp0_stage3_iter0();
    void thread_ap_block_state6_pp0_stage0_iter1();
    void thread_ap_block_state7_pp0_stage1_iter1();
    void thread_ap_block_state8_pp0_stage2_iter1();
    void thread_ap_block_state9_pp0_stage3_iter1();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_k_0_phi_fu_284_p4();
    void thread_ap_ready();
    void thread_dct_coeff_table_0_address0();
    void thread_dct_coeff_table_0_ce0();
    void thread_dct_coeff_table_1_address0();
    void thread_dct_coeff_table_1_ce0();
    void thread_dct_coeff_table_2_address0();
    void thread_dct_coeff_table_2_ce0();
    void thread_dct_coeff_table_3_address0();
    void thread_dct_coeff_table_3_ce0();
    void thread_dct_coeff_table_4_address0();
    void thread_dct_coeff_table_4_ce0();
    void thread_dct_coeff_table_5_address0();
    void thread_dct_coeff_table_5_ce0();
    void thread_dct_coeff_table_6_address0();
    void thread_dct_coeff_table_6_ce0();
    void thread_dct_coeff_table_7_address0();
    void thread_dct_coeff_table_7_ce0();
    void thread_dst_address0();
    void thread_dst_ce0();
    void thread_dst_d0();
    void thread_dst_we0();
    void thread_grp_fu_563_p2();
    void thread_grp_fu_571_p1();
    void thread_grp_fu_571_p10();
    void thread_icmp_ln11_fu_429_p2();
    void thread_k_fu_435_p2();
    void thread_or_ln17_1_fu_339_p2();
    void thread_or_ln17_2_fu_354_p2();
    void thread_or_ln17_3_fu_369_p2();
    void thread_or_ln17_4_fu_384_p2();
    void thread_or_ln17_5_fu_399_p2();
    void thread_or_ln17_6_fu_414_p2();
    void thread_or_ln17_fu_324_p2();
    void thread_src_address0();
    void thread_src_address1();
    void thread_src_ce0();
    void thread_src_ce1();
    void thread_tmp_1_fu_405_p3();
    void thread_tmp_2_fu_420_p3();
    void thread_tmp_4_fu_299_p3();
    void thread_tmp_5_fu_311_p3();
    void thread_tmp_6_fu_330_p3();
    void thread_tmp_7_fu_345_p3();
    void thread_tmp_8_fu_360_p3();
    void thread_tmp_9_fu_375_p3();
    void thread_tmp_s_fu_390_p3();
    void thread_zext_ln16_fu_441_p1();
    void thread_zext_ln17_1_fu_319_p1();
    void thread_zext_ln17_2_fu_307_p1();
    void thread_zext_ln19_1_fu_541_p1();
    void thread_zext_ln19_fu_453_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
