-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_1d is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src_ce0 : OUT STD_LOGIC;
    src_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src1_ce0 : OUT STD_LOGIC;
    src1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src2_ce0 : OUT STD_LOGIC;
    src2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src3_ce0 : OUT STD_LOGIC;
    src3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src4_ce0 : OUT STD_LOGIC;
    src4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src5_ce0 : OUT STD_LOGIC;
    src5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src6_ce0 : OUT STD_LOGIC;
    src6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    src7_ce0 : OUT STD_LOGIC;
    src7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src_offset : IN STD_LOGIC_VECTOR (3 downto 0);
    dst_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    dst_ce0 : OUT STD_LOGIC;
    dst_we0 : OUT STD_LOGIC;
    dst_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_offset : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of dct_1d is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv29_1000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dct_coeff_table_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_0_ce0 : STD_LOGIC;
    signal dct_coeff_table_0_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal dct_coeff_table_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_1_ce0 : STD_LOGIC;
    signal dct_coeff_table_1_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_2_ce0 : STD_LOGIC;
    signal dct_coeff_table_2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_3_ce0 : STD_LOGIC;
    signal dct_coeff_table_3_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_4_ce0 : STD_LOGIC;
    signal dct_coeff_table_4_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_5_ce0 : STD_LOGIC;
    signal dct_coeff_table_5_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_6_ce0 : STD_LOGIC;
    signal dct_coeff_table_6_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_7_ce0 : STD_LOGIC;
    signal dct_coeff_table_7_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal k_0_reg_307 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_0_reg_307_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal k_0_reg_307_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal k_0_reg_307_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln19_cast_fu_327_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln19_cast_reg_506 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_addr_reg_511 : STD_LOGIC_VECTOR (2 downto 0);
    signal src1_addr_reg_516 : STD_LOGIC_VECTOR (2 downto 0);
    signal src2_addr_reg_521 : STD_LOGIC_VECTOR (2 downto 0);
    signal src3_addr_reg_526 : STD_LOGIC_VECTOR (2 downto 0);
    signal src4_addr_reg_531 : STD_LOGIC_VECTOR (2 downto 0);
    signal src5_addr_reg_536 : STD_LOGIC_VECTOR (2 downto 0);
    signal src6_addr_reg_541 : STD_LOGIC_VECTOR (2 downto 0);
    signal src7_addr_reg_546 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln11_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_551_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_551_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_551_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_551_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_fu_349_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_reg_555 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal dct_coeff_table_0_lo_reg_600 : STD_LOGIC_VECTOR (13 downto 0);
    signal dct_coeff_table_0_lo_reg_600_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal dct_coeff_table_1_lo_reg_605 : STD_LOGIC_VECTOR (14 downto 0);
    signal src1_load_reg_610 : STD_LOGIC_VECTOR (15 downto 0);
    signal dct_coeff_table_2_lo_reg_615 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_2_lo_reg_615_pp0_iter2_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_3_lo_reg_620 : STD_LOGIC_VECTOR (14 downto 0);
    signal src3_load_reg_625 : STD_LOGIC_VECTOR (15 downto 0);
    signal dct_coeff_table_4_lo_reg_630 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_4_lo_reg_630_pp0_iter2_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_5_lo_reg_635 : STD_LOGIC_VECTOR (14 downto 0);
    signal src5_load_reg_640 : STD_LOGIC_VECTOR (15 downto 0);
    signal dct_coeff_table_6_lo_reg_645 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_6_lo_reg_645_pp0_iter2_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_7_lo_reg_650 : STD_LOGIC_VECTOR (14 downto 0);
    signal src7_load_reg_655 : STD_LOGIC_VECTOR (15 downto 0);
    signal src_load_reg_660 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln17_1_fu_452_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln17_1_reg_665 : STD_LOGIC_VECTOR (28 downto 0);
    signal src2_load_reg_670 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln17_3_fu_458_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln17_3_reg_675 : STD_LOGIC_VECTOR (28 downto 0);
    signal src4_load_reg_680 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln17_5_fu_464_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln17_5_reg_685 : STD_LOGIC_VECTOR (28 downto 0);
    signal src6_load_reg_690 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_470_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_5_reg_695 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal grp_fu_478_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_1_reg_700 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal grp_fu_485_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_2_reg_705 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_492_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_4_reg_710 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_499_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_6_reg_715 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln19_8_fu_419_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln19_8_reg_720 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_725 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_phi_mux_k_0_phi_fu_311_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal src_offset_cast_fu_331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_fu_355_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_1_fu_448_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_319_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln19_fu_415_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln19_3_fu_424_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln19_3_fu_424_p2 : signal is "no";
    signal add_ln19_7_fu_428_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln19_7_fu_428_p2 : signal is "no";
    signal add_ln19_fu_432_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_470_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_478_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_478_p10 : STD_LOGIC_VECTOR (28 downto 0);

    component dct_mul_mul_16s_1jbC IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16kbM IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16lbW IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16mb6 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_1d_dct_coeff_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component dct_1d_dct_coeff_cud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_fYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_g8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_hbi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_1d_dct_coeff_ibs IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    dct_coeff_table_0_U : component dct_1d_dct_coeff_bkb
    generic map (
        DataWidth => 14,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_0_address0,
        ce0 => dct_coeff_table_0_ce0,
        q0 => dct_coeff_table_0_q0);

    dct_coeff_table_1_U : component dct_1d_dct_coeff_cud
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_1_address0,
        ce0 => dct_coeff_table_1_ce0,
        q0 => dct_coeff_table_1_q0);

    dct_coeff_table_2_U : component dct_1d_dct_coeff_dEe
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_2_address0,
        ce0 => dct_coeff_table_2_ce0,
        q0 => dct_coeff_table_2_q0);

    dct_coeff_table_3_U : component dct_1d_dct_coeff_eOg
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_3_address0,
        ce0 => dct_coeff_table_3_ce0,
        q0 => dct_coeff_table_3_q0);

    dct_coeff_table_4_U : component dct_1d_dct_coeff_fYi
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_4_address0,
        ce0 => dct_coeff_table_4_ce0,
        q0 => dct_coeff_table_4_q0);

    dct_coeff_table_5_U : component dct_1d_dct_coeff_g8j
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_5_address0,
        ce0 => dct_coeff_table_5_ce0,
        q0 => dct_coeff_table_5_q0);

    dct_coeff_table_6_U : component dct_1d_dct_coeff_hbi
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_6_address0,
        ce0 => dct_coeff_table_6_ce0,
        q0 => dct_coeff_table_6_q0);

    dct_coeff_table_7_U : component dct_1d_dct_coeff_ibs
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_7_address0,
        ce0 => dct_coeff_table_7_ce0,
        q0 => dct_coeff_table_7_q0);

    dct_mul_mul_16s_1jbC_U10 : component dct_mul_mul_16s_1jbC
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => src1_load_reg_610,
        din1 => dct_coeff_table_1_lo_reg_605,
        dout => mul_ln17_1_fu_452_p2);

    dct_mul_mul_16s_1jbC_U11 : component dct_mul_mul_16s_1jbC
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => src3_load_reg_625,
        din1 => dct_coeff_table_3_lo_reg_620,
        dout => mul_ln17_3_fu_458_p2);

    dct_mul_mul_16s_1jbC_U12 : component dct_mul_mul_16s_1jbC
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => src5_load_reg_640,
        din1 => dct_coeff_table_5_lo_reg_635,
        dout => mul_ln17_5_fu_464_p2);

    dct_mac_muladd_16kbM_U13 : component dct_mac_muladd_16kbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 14,
        dout_WIDTH => 29)
    port map (
        din0 => src7_load_reg_655,
        din1 => dct_coeff_table_7_lo_reg_650,
        din2 => grp_fu_470_p2,
        dout => grp_fu_470_p3);

    dct_mac_muladd_16lbW_U14 : component dct_mac_muladd_16lbW
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        din0 => src_load_reg_660,
        din1 => grp_fu_478_p1,
        din2 => mul_ln17_1_reg_665,
        dout => grp_fu_478_p3);

    dct_mac_muladd_16mb6_U15 : component dct_mac_muladd_16mb6
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        din0 => src2_load_reg_670,
        din1 => dct_coeff_table_2_lo_reg_615_pp0_iter2_reg,
        din2 => mul_ln17_3_reg_675,
        dout => grp_fu_485_p3);

    dct_mac_muladd_16mb6_U16 : component dct_mac_muladd_16mb6
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        din0 => src4_load_reg_680,
        din1 => dct_coeff_table_4_lo_reg_630_pp0_iter2_reg,
        din2 => mul_ln17_5_reg_685,
        dout => grp_fu_492_p3);

    dct_mac_muladd_16mb6_U17 : component dct_mac_muladd_16mb6
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        din0 => src6_load_reg_690,
        din1 => dct_coeff_table_6_lo_reg_645_pp0_iter2_reg,
        din2 => add_ln19_5_reg_695,
        dout => grp_fu_499_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_0_reg_307_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln11_reg_551 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_0_reg_307 <= k_reg_555;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_0_reg_307 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln11_reg_551_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln19_1_reg_700 <= grp_fu_478_p3;
                add_ln19_2_reg_705 <= grp_fu_485_p3;
                add_ln19_4_reg_710 <= grp_fu_492_p3;
                add_ln19_6_reg_715 <= grp_fu_499_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln11_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln19_5_reg_695 <= grp_fu_470_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln11_reg_551_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln19_8_reg_720 <= add_ln19_8_fu_419_p2;
                trunc_ln_reg_725 <= add_ln19_fu_432_p2(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln11_reg_551 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                dct_coeff_table_0_lo_reg_600 <= dct_coeff_table_0_q0;
                dct_coeff_table_1_lo_reg_605 <= dct_coeff_table_1_q0;
                dct_coeff_table_2_lo_reg_615 <= dct_coeff_table_2_q0;
                dct_coeff_table_3_lo_reg_620 <= dct_coeff_table_3_q0;
                dct_coeff_table_4_lo_reg_630 <= dct_coeff_table_4_q0;
                dct_coeff_table_5_lo_reg_635 <= dct_coeff_table_5_q0;
                dct_coeff_table_6_lo_reg_645 <= dct_coeff_table_6_q0;
                dct_coeff_table_7_lo_reg_650 <= dct_coeff_table_7_q0;
                src1_load_reg_610 <= src1_q0;
                src3_load_reg_625 <= src3_q0;
                src5_load_reg_640 <= src5_q0;
                src7_load_reg_655 <= src7_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                dct_coeff_table_0_lo_reg_600_pp0_iter2_reg <= dct_coeff_table_0_lo_reg_600;
                dct_coeff_table_2_lo_reg_615_pp0_iter2_reg <= dct_coeff_table_2_lo_reg_615;
                dct_coeff_table_4_lo_reg_630_pp0_iter2_reg <= dct_coeff_table_4_lo_reg_630;
                dct_coeff_table_6_lo_reg_645_pp0_iter2_reg <= dct_coeff_table_6_lo_reg_645;
                icmp_ln11_reg_551_pp0_iter2_reg <= icmp_ln11_reg_551_pp0_iter1_reg;
                icmp_ln11_reg_551_pp0_iter3_reg <= icmp_ln11_reg_551_pp0_iter2_reg;
                icmp_ln11_reg_551_pp0_iter4_reg <= icmp_ln11_reg_551_pp0_iter3_reg;
                k_0_reg_307_pp0_iter2_reg <= k_0_reg_307_pp0_iter1_reg;
                k_0_reg_307_pp0_iter3_reg <= k_0_reg_307_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln11_reg_551 <= icmp_ln11_fu_343_p2;
                icmp_ln11_reg_551_pp0_iter1_reg <= icmp_ln11_reg_551;
                k_0_reg_307_pp0_iter1_reg <= k_0_reg_307;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                k_reg_555 <= k_fu_349_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln11_reg_551_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln17_1_reg_665 <= mul_ln17_1_fu_452_p2;
                mul_ln17_3_reg_675 <= mul_ln17_3_fu_458_p2;
                mul_ln17_5_reg_685 <= mul_ln17_5_fu_464_p2;
                src2_load_reg_670 <= src2_q0;
                src4_load_reg_680 <= src4_q0;
                src6_load_reg_690 <= src6_q0;
                src_load_reg_660 <= src_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                src1_addr_reg_516 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src2_addr_reg_521 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src3_addr_reg_526 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src4_addr_reg_531 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src5_addr_reg_536 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src6_addr_reg_541 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src7_addr_reg_546 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                src_addr_reg_511 <= src_offset_cast_fu_331_p1(3 - 1 downto 0);
                    zext_ln19_cast_reg_506(6 downto 3) <= zext_ln19_cast_fu_327_p1(6 downto 3);
            end if;
        end if;
    end process;
    zext_ln19_cast_reg_506(2 downto 0) <= "000";
    zext_ln19_cast_reg_506(7) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln11_fu_343_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln11_fu_343_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln11_fu_343_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln19_3_fu_424_p2 <= std_logic_vector(signed(add_ln19_1_reg_700) + signed(add_ln19_2_reg_705));
    add_ln19_7_fu_428_p2 <= std_logic_vector(signed(add_ln19_4_reg_710) + signed(add_ln19_6_reg_715));
    add_ln19_8_fu_419_p2 <= std_logic_vector(unsigned(zext_ln19_cast_reg_506) + unsigned(zext_ln19_fu_415_p1));
    add_ln19_fu_432_p2 <= std_logic_vector(unsigned(add_ln19_3_fu_424_p2) + unsigned(add_ln19_7_fu_428_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln11_fu_343_p2)
    begin
        if ((icmp_ln11_fu_343_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_k_0_phi_fu_311_p4_assign_proc : process(k_0_reg_307, ap_CS_fsm_pp0_stage0, icmp_ln11_reg_551, k_reg_555, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln11_reg_551 = ap_const_lv1_0))) then 
            ap_phi_mux_k_0_phi_fu_311_p4 <= k_reg_555;
        else 
            ap_phi_mux_k_0_phi_fu_311_p4 <= k_0_reg_307;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_0_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_0_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_1_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_1_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_2_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_2_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_3_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_3_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_4_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_4_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_5_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_5_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_6_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_6_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dct_coeff_table_7_address0 <= zext_ln16_fu_355_p1(3 - 1 downto 0);

    dct_coeff_table_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dct_coeff_table_7_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dst_address0 <= zext_ln19_1_fu_448_p1(6 - 1 downto 0);

    dst_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dst_ce0 <= ap_const_logic_1;
        else 
            dst_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dst_d0 <= trunc_ln_reg_725;

    dst_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln11_reg_551_pp0_iter4_reg, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln11_reg_551_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dst_we0 <= ap_const_logic_1;
        else 
            dst_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_470_p2 <= ap_const_lv29_1000(14 - 1 downto 0);
    grp_fu_478_p1 <= grp_fu_478_p10(14 - 1 downto 0);
    grp_fu_478_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dct_coeff_table_0_lo_reg_600_pp0_iter2_reg),29));
    icmp_ln11_fu_343_p2 <= "1" when (ap_phi_mux_k_0_phi_fu_311_p4 = ap_const_lv4_8) else "0";
    k_fu_349_p2 <= std_logic_vector(unsigned(ap_phi_mux_k_0_phi_fu_311_p4) + unsigned(ap_const_lv4_1));
    src1_address0 <= src1_addr_reg_516;

    src1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src1_ce0 <= ap_const_logic_1;
        else 
            src1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src2_address0 <= src2_addr_reg_521;

    src2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src2_ce0 <= ap_const_logic_1;
        else 
            src2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src3_address0 <= src3_addr_reg_526;

    src3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src3_ce0 <= ap_const_logic_1;
        else 
            src3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src4_address0 <= src4_addr_reg_531;

    src4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src4_ce0 <= ap_const_logic_1;
        else 
            src4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src5_address0 <= src5_addr_reg_536;

    src5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src5_ce0 <= ap_const_logic_1;
        else 
            src5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src6_address0 <= src6_addr_reg_541;

    src6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src6_ce0 <= ap_const_logic_1;
        else 
            src6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src7_address0 <= src7_addr_reg_546;

    src7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src7_ce0 <= ap_const_logic_1;
        else 
            src7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src_address0 <= src_addr_reg_511;

    src_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src_ce0 <= ap_const_logic_1;
        else 
            src_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src_offset_cast_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_offset),64));
    tmp_3_fu_319_p3 <= (dst_offset & ap_const_lv3_0);
    zext_ln16_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_k_0_phi_fu_311_p4),64));
    zext_ln19_1_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln19_8_reg_720),64));
    zext_ln19_cast_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_319_p3),8));
    zext_ln19_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_307_pp0_iter3_reg),8));
end behav;
