// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "lab1_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic lab1_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic lab1_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> lab1_1::ap_ST_fsm_state1 = "1";
const sc_lv<3> lab1_1::ap_ST_fsm_state2 = "10";
const sc_lv<3> lab1_1::ap_ST_fsm_state3 = "100";
const sc_lv<32> lab1_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> lab1_1::ap_const_lv32_1 = "1";
const sc_lv<32> lab1_1::ap_const_lv32_2 = "10";
const bool lab1_1::ap_const_boolean_1 = true;

lab1_1::lab1_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lab1_1_mac_muladdbkb_U1 = new lab1_1_mac_muladdbkb<1,3,8,8,9,16>("lab1_1_mac_muladdbkb_U1");
    lab1_1_mac_muladdbkb_U1->clk(ap_clk);
    lab1_1_mac_muladdbkb_U1->reset(ap_rst);
    lab1_1_mac_muladdbkb_U1->din0(b);
    lab1_1_mac_muladdbkb_U1->din1(a);
    lab1_1_mac_muladdbkb_U1->din2(add_ln3_reg_89);
    lab1_1_mac_muladdbkb_U1->ce(ap_var_for_const0);
    lab1_1_mac_muladdbkb_U1->dout(grp_fu_70_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln3_fu_58_p2);
    sensitive << ( sext_ln3_2_fu_50_p1 );
    sensitive << ( sext_ln3_3_fu_54_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_70_p3 );

    SC_METHOD(thread_sext_ln3_2_fu_50_p1);
    sensitive << ( c );

    SC_METHOD(thread_sext_ln3_3_fu_54_p1);
    sensitive << ( d );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "lab1_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, c, "(port)c");
    sc_trace(mVcdFile, d, "(port)d");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln3_fu_58_p2, "add_ln3_fu_58_p2");
    sc_trace(mVcdFile, add_ln3_reg_89, "add_ln3_reg_89");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sext_ln3_2_fu_50_p1, "sext_ln3_2_fu_50_p1");
    sc_trace(mVcdFile, sext_ln3_3_fu_54_p1, "sext_ln3_3_fu_54_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_fu_70_p3, "grp_fu_70_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("lab1_1.hdltvin.dat");
    mHdltvoutHandle.open("lab1_1.hdltvout.dat");
}

lab1_1::~lab1_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete lab1_1_mac_muladdbkb_U1;
}

void lab1_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void lab1_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln3_reg_89 = add_ln3_fu_58_p2.read();
    }
}

void lab1_1::thread_add_ln3_fu_58_p2() {
    add_ln3_fu_58_p2 = (!sext_ln3_2_fu_50_p1.read().is_01() || !sext_ln3_3_fu_54_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln3_2_fu_50_p1.read()) + sc_bigint<9>(sext_ln3_3_fu_54_p1.read()));
}

void lab1_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void lab1_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void lab1_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void lab1_1::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void lab1_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void lab1_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void lab1_1::thread_ap_return() {
    ap_return = esl_sext<32,16>(grp_fu_70_p3.read());
}

void lab1_1::thread_sext_ln3_2_fu_50_p1() {
    sext_ln3_2_fu_50_p1 = esl_sext<9,8>(c.read());
}

void lab1_1::thread_sext_ln3_3_fu_54_p1() {
    sext_ln3_3_fu_54_p1 = esl_sext<9,8>(d.read());
}

void lab1_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void lab1_1::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a\" :  \"" << a.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"c\" :  \"" << c.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d\" :  \"" << d.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

