-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dct,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.790000,HLS_SYN_LAT=899,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=8,HLS_SYN_FF=1476,HLS_SYN_LUT=1735,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten_reg_136 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_0_i_reg_147 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_i_reg_158 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten11_reg_169 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_0_i2_reg_180 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_i4_reg_191 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln59_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln59_reg_415_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_reg_415_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_fu_230_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal select_ln59_fu_248_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_reg_424 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_reg_424_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_reg_424_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_1_fu_256_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_1_reg_430 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_1_reg_430_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln59_1_reg_430_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln59_fu_264_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln59_reg_436 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_fu_268_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal input_load_reg_451 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln71_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state8_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp1_stage0_iter2 : BOOLEAN;
    signal ap_block_state11_pp1_stage0_iter3 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal icmp_ln71_reg_456_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_reg_456_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln71_fu_326_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal select_ln71_fu_344_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln71_reg_465 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln71_1_fu_352_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln71_1_reg_471 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln71_fu_360_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln71_reg_477 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_fu_364_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln74_fu_405_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln74_reg_492 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln74_reg_492_pp1_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_out_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_out_load_reg_497 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_dct_2d_fu_202_ap_ready : STD_LOGIC;
    signal grp_dct_2d_fu_202_ap_done : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state8 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp1_iter3 : STD_LOGIC := '0';
    signal buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_in_ce0 : STD_LOGIC;
    signal buf_2d_in_we0 : STD_LOGIC;
    signal buf_2d_in_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce1 : STD_LOGIC;
    signal buf_2d_in_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_out_ce0 : STD_LOGIC;
    signal buf_2d_out_we0 : STD_LOGIC;
    signal grp_dct_2d_fu_202_ap_start : STD_LOGIC;
    signal grp_dct_2d_fu_202_ap_idle : STD_LOGIC;
    signal grp_dct_2d_fu_202_in_block_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_202_in_block_ce0 : STD_LOGIC;
    signal grp_dct_2d_fu_202_in_block_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_202_in_block_ce1 : STD_LOGIC;
    signal grp_dct_2d_fu_202_out_block_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_202_out_block_ce0 : STD_LOGIC;
    signal grp_dct_2d_fu_202_out_block_we0 : STD_LOGIC;
    signal grp_dct_2d_fu_202_out_block_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_r_0_i_phi_fu_151_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_r_0_i2_phi_fu_184_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal grp_dct_2d_fu_202_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln62_fu_290_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln62_2_fu_315_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_1_fu_400_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_2_fu_411_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln61_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_236_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln61_fu_281_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln62_mid2_fu_274_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln62_fu_284_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_295_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln61_1_fu_302_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln62_1_fu_306_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln62_1_fu_309_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln73_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_332_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_370_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln71_fu_377_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln74_fu_391_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_1_fu_394_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln73_fu_388_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln74_mid2_fu_381_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;

    component dct_2d IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_block_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        in_block_ce0 : OUT STD_LOGIC;
        in_block_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        in_block_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        in_block_ce1 : OUT STD_LOGIC;
        in_block_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        out_block_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        out_block_ce0 : OUT STD_LOGIC;
        out_block_we0 : OUT STD_LOGIC;
        out_block_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_2d_col_inbuf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_2d_row_outbuf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    buf_2d_in_U : component dct_2d_col_inbuf
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_in_address0,
        ce0 => buf_2d_in_ce0,
        we0 => buf_2d_in_we0,
        d0 => input_load_reg_451,
        q0 => buf_2d_in_q0,
        address1 => grp_dct_2d_fu_202_in_block_address1,
        ce1 => buf_2d_in_ce1,
        q1 => buf_2d_in_q1);

    buf_2d_out_U : component dct_2d_row_outbuf
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_out_address0,
        ce0 => buf_2d_out_ce0,
        we0 => buf_2d_out_we0,
        d0 => grp_dct_2d_fu_202_out_block_d0,
        q0 => buf_2d_out_q0);

    grp_dct_2d_fu_202 : component dct_2d
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_2d_fu_202_ap_start,
        ap_done => grp_dct_2d_fu_202_ap_done,
        ap_idle => grp_dct_2d_fu_202_ap_idle,
        ap_ready => grp_dct_2d_fu_202_ap_ready,
        in_block_address0 => grp_dct_2d_fu_202_in_block_address0,
        in_block_ce0 => grp_dct_2d_fu_202_in_block_ce0,
        in_block_q0 => buf_2d_in_q0,
        in_block_address1 => grp_dct_2d_fu_202_in_block_address1,
        in_block_ce1 => grp_dct_2d_fu_202_in_block_ce1,
        in_block_q1 => buf_2d_in_q1,
        out_block_address0 => grp_dct_2d_fu_202_out_block_address0,
        out_block_ce0 => grp_dct_2d_fu_202_out_block_ce0,
        out_block_we0 => grp_dct_2d_fu_202_out_block_we0,
        out_block_d0 => grp_dct_2d_fu_202_out_block_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp1_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp1_exit_iter0_state8)) then 
                        ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state8);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_2d_fu_202_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_2d_fu_202_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_dct_2d_fu_202_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_2d_fu_202_ap_ready = ap_const_logic_1)) then 
                    grp_dct_2d_fu_202_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_0_i4_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_320_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                c_0_i4_reg_191 <= c_1_fu_364_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then 
                c_0_i4_reg_191 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    c_0_i_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln59_fu_224_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                c_0_i_reg_158 <= c_fu_268_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_0_i_reg_158 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    indvar_flatten11_reg_169_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_320_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                indvar_flatten11_reg_169 <= add_ln71_fu_326_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then 
                indvar_flatten11_reg_169 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln59_fu_224_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_136 <= add_ln59_fu_230_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_136 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    r_0_i2_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_456 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
                r_0_i2_reg_180 <= select_ln71_1_reg_471;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then 
                r_0_i2_reg_180 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    r_0_i_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln59_reg_415 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                r_0_i_reg_147 <= select_ln59_1_reg_430;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_0_i_reg_147 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_456 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                add_ln74_reg_492 <= add_ln74_fu_405_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp1_stage0_11001)) then
                add_ln74_reg_492_pp1_iter2_reg <= add_ln74_reg_492;
                icmp_ln71_reg_456_pp1_iter2_reg <= icmp_ln71_reg_456_pp1_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_456_pp1_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                buf_2d_out_load_reg_497 <= buf_2d_out_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln59_reg_415 <= icmp_ln59_fu_224_p2;
                icmp_ln59_reg_415_pp0_iter1_reg <= icmp_ln59_reg_415;
                select_ln59_1_reg_430_pp0_iter1_reg <= select_ln59_1_reg_430;
                select_ln59_reg_424_pp0_iter1_reg <= select_ln59_reg_424;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln59_reg_415_pp0_iter2_reg <= icmp_ln59_reg_415_pp0_iter1_reg;
                select_ln59_1_reg_430_pp0_iter2_reg <= select_ln59_1_reg_430_pp0_iter1_reg;
                select_ln59_reg_424_pp0_iter2_reg <= select_ln59_reg_424_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln71_reg_456 <= icmp_ln71_fu_320_p2;
                icmp_ln71_reg_456_pp1_iter1_reg <= icmp_ln71_reg_456;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln59_reg_415_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                input_load_reg_451 <= input_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln59_fu_224_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln59_1_reg_430 <= select_ln59_1_fu_256_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln59_fu_224_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln59_reg_424 <= select_ln59_fu_248_p3;
                trunc_ln59_reg_436 <= trunc_ln59_fu_264_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_320_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                select_ln71_1_reg_471 <= select_ln71_1_fu_352_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_320_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                select_ln71_reg_465 <= select_ln71_fu_344_p3;
                trunc_ln71_reg_477 <= trunc_ln71_fu_360_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln59_fu_224_p2, ap_enable_reg_pp0_iter0, icmp_ln71_fu_320_p2, ap_enable_reg_pp1_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_state7, grp_dct_2d_fu_202_ap_done, ap_block_pp1_stage0_subdone, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter2, ap_enable_reg_pp1_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln59_fu_224_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln59_fu_224_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dct_2d_fu_202_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if ((not(((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln71_fu_320_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif ((((ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) or ((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln71_fu_320_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln59_fu_230_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_136) + unsigned(ap_const_lv7_1));
    add_ln62_1_fu_309_p2 <= std_logic_vector(unsigned(zext_ln61_1_fu_302_p1) + unsigned(zext_ln62_1_fu_306_p1));
    add_ln62_fu_284_p2 <= std_logic_vector(unsigned(zext_ln61_fu_281_p1) + unsigned(shl_ln62_mid2_fu_274_p3));
    add_ln71_fu_326_p2 <= std_logic_vector(unsigned(indvar_flatten11_reg_169) + unsigned(ap_const_lv7_1));
    add_ln74_1_fu_394_p2 <= std_logic_vector(unsigned(zext_ln71_fu_377_p1) + unsigned(zext_ln74_fu_391_p1));
    add_ln74_fu_405_p2 <= std_logic_vector(unsigned(zext_ln73_fu_388_p1) + unsigned(shl_ln74_mid2_fu_381_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(5);
    ap_CS_fsm_state6 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp1_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp1_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln59_fu_224_p2)
    begin
        if ((icmp_ln59_fu_224_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state8_assign_proc : process(icmp_ln71_fu_320_p2)
    begin
        if ((icmp_ln71_fu_320_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter2, ap_enable_reg_pp1_iter3)
    begin
        if (((ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_r_0_i2_phi_fu_184_p4_assign_proc : process(r_0_i2_reg_180, icmp_ln71_reg_456, ap_CS_fsm_pp1_stage0, select_ln71_1_reg_471, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((icmp_ln71_reg_456 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_r_0_i2_phi_fu_184_p4 <= select_ln71_1_reg_471;
        else 
            ap_phi_mux_r_0_i2_phi_fu_184_p4 <= r_0_i2_reg_180;
        end if; 
    end process;


    ap_phi_mux_r_0_i_phi_fu_151_p4_assign_proc : process(r_0_i_reg_147, icmp_ln59_reg_415, ap_CS_fsm_pp0_stage0, select_ln59_1_reg_430, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln59_reg_415 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_r_0_i_phi_fu_151_p4 <= select_ln59_1_reg_430;
        else 
            ap_phi_mux_r_0_i_phi_fu_151_p4 <= r_0_i_reg_147;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_address0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_state7, grp_dct_2d_fu_202_in_block_address0, ap_block_pp0_stage0, zext_ln62_2_fu_315_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_2d_in_address0 <= zext_ln62_2_fu_315_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_in_address0 <= grp_dct_2d_fu_202_in_block_address0;
        else 
            buf_2d_in_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_in_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3, ap_CS_fsm_state7, grp_dct_2d_fu_202_in_block_ce0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_2d_in_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_in_ce0 <= grp_dct_2d_fu_202_in_block_ce0;
        else 
            buf_2d_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce1_assign_proc : process(ap_CS_fsm_state7, grp_dct_2d_fu_202_in_block_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_in_ce1 <= grp_dct_2d_fu_202_in_block_ce1;
        else 
            buf_2d_in_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln59_reg_415_pp0_iter2_reg, ap_enable_reg_pp0_iter3)
    begin
        if (((icmp_ln59_reg_415_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_2d_in_we0 <= ap_const_logic_1;
        else 
            buf_2d_in_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_state7, ap_enable_reg_pp1_iter1, grp_dct_2d_fu_202_out_block_address0, ap_block_pp1_stage0, zext_ln74_1_fu_400_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            buf_2d_out_address0 <= zext_ln74_1_fu_400_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_out_address0 <= grp_dct_2d_fu_202_out_block_address0;
        else 
            buf_2d_out_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_out_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_CS_fsm_state7, ap_enable_reg_pp1_iter1, grp_dct_2d_fu_202_out_block_ce0)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            buf_2d_out_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_out_ce0 <= grp_dct_2d_fu_202_out_block_ce0;
        else 
            buf_2d_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_we0_assign_proc : process(ap_CS_fsm_state7, grp_dct_2d_fu_202_out_block_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_out_we0 <= grp_dct_2d_fu_202_out_block_we0;
        else 
            buf_2d_out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    c_1_fu_364_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(select_ln71_fu_344_p3));
    c_fu_268_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(select_ln59_fu_248_p3));
    grp_dct_2d_fu_202_ap_start <= grp_dct_2d_fu_202_ap_start_reg;
    icmp_ln59_fu_224_p2 <= "1" when (indvar_flatten_reg_136 = ap_const_lv7_40) else "0";
    icmp_ln61_fu_242_p2 <= "1" when (c_0_i_reg_158 = ap_const_lv4_8) else "0";
    icmp_ln71_fu_320_p2 <= "1" when (indvar_flatten11_reg_169 = ap_const_lv7_40) else "0";
    icmp_ln73_fu_338_p2 <= "1" when (c_0_i4_reg_191 = ap_const_lv4_8) else "0";
    input_r_address0 <= zext_ln62_fu_290_p1(6 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_address0 <= zext_ln74_2_fu_411_p1(6 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter3)
    begin
        if (((ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= buf_2d_out_load_reg_497;

    output_r_we0_assign_proc : process(ap_block_pp1_stage0_11001, icmp_ln71_reg_456_pp1_iter2_reg, ap_enable_reg_pp1_iter3)
    begin
        if (((icmp_ln71_reg_456_pp1_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    r_1_fu_332_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(ap_phi_mux_r_0_i2_phi_fu_184_p4));
    r_fu_236_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(ap_phi_mux_r_0_i_phi_fu_151_p4));
    select_ln59_1_fu_256_p3 <= 
        r_fu_236_p2 when (icmp_ln61_fu_242_p2(0) = '1') else 
        ap_phi_mux_r_0_i_phi_fu_151_p4;
    select_ln59_fu_248_p3 <= 
        ap_const_lv4_0 when (icmp_ln61_fu_242_p2(0) = '1') else 
        c_0_i_reg_158;
    select_ln71_1_fu_352_p3 <= 
        r_1_fu_332_p2 when (icmp_ln73_fu_338_p2(0) = '1') else 
        ap_phi_mux_r_0_i2_phi_fu_184_p4;
    select_ln71_fu_344_p3 <= 
        ap_const_lv4_0 when (icmp_ln73_fu_338_p2(0) = '1') else 
        c_0_i4_reg_191;
    shl_ln62_mid2_fu_274_p3 <= (trunc_ln59_reg_436 & ap_const_lv3_0);
    shl_ln74_mid2_fu_381_p3 <= (trunc_ln71_reg_477 & ap_const_lv3_0);
    tmp_3_fu_370_p3 <= (select_ln71_1_reg_471 & ap_const_lv3_0);
    tmp_s_fu_295_p3 <= (select_ln59_1_reg_430_pp0_iter2_reg & ap_const_lv3_0);
    trunc_ln59_fu_264_p1 <= select_ln59_1_fu_256_p3(3 - 1 downto 0);
    trunc_ln71_fu_360_p1 <= select_ln71_1_fu_352_p3(3 - 1 downto 0);
    zext_ln61_1_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_295_p3),8));
    zext_ln61_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln59_reg_424),6));
    zext_ln62_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln59_reg_424_pp0_iter2_reg),8));
    zext_ln62_2_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln62_1_fu_309_p2),64));
    zext_ln62_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln62_fu_284_p2),64));
    zext_ln71_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_370_p3),8));
    zext_ln73_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln71_reg_465),6));
    zext_ln74_1_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_1_fu_394_p2),64));
    zext_ln74_2_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_reg_492_pp1_iter2_reg),64));
    zext_ln74_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln71_reg_465),8));
end behav;
