// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> dct::ap_ST_fsm_state1 = "1";
const sc_lv<6> dct::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> dct::ap_ST_fsm_state4 = "100";
const sc_lv<6> dct::ap_ST_fsm_state5 = "1000";
const sc_lv<6> dct::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<6> dct::ap_ST_fsm_state8 = "100000";
const sc_lv<32> dct::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool dct::ap_const_boolean_1 = true;
const sc_lv<32> dct::ap_const_lv32_1 = "1";
const bool dct::ap_const_boolean_0 = false;
const sc_lv<1> dct::ap_const_lv1_0 = "0";
const sc_lv<32> dct::ap_const_lv32_4 = "100";
const sc_lv<1> dct::ap_const_lv1_1 = "1";
const sc_lv<32> dct::ap_const_lv32_3 = "11";
const sc_lv<7> dct::ap_const_lv7_0 = "0000000";
const sc_lv<4> dct::ap_const_lv4_0 = "0000";
const sc_lv<32> dct::ap_const_lv32_2 = "10";
const sc_lv<7> dct::ap_const_lv7_40 = "1000000";
const sc_lv<7> dct::ap_const_lv7_1 = "1";
const sc_lv<4> dct::ap_const_lv4_1 = "1";
const sc_lv<4> dct::ap_const_lv4_8 = "1000";
const sc_lv<3> dct::ap_const_lv3_0 = "000";
const sc_lv<32> dct::ap_const_lv32_5 = "101";

dct::dct(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_2d_in_U = new dct_2d_row_outbuf("buf_2d_in_U");
    buf_2d_in_U->clk(ap_clk);
    buf_2d_in_U->reset(ap_rst);
    buf_2d_in_U->address0(buf_2d_in_address0);
    buf_2d_in_U->ce0(buf_2d_in_ce0);
    buf_2d_in_U->we0(buf_2d_in_we0);
    buf_2d_in_U->d0(input_r_q0);
    buf_2d_in_U->q0(buf_2d_in_q0);
    buf_2d_out_U = new dct_2d_row_outbuf("buf_2d_out_U");
    buf_2d_out_U->clk(ap_clk);
    buf_2d_out_U->reset(ap_rst);
    buf_2d_out_U->address0(buf_2d_out_address0);
    buf_2d_out_U->ce0(buf_2d_out_ce0);
    buf_2d_out_U->we0(buf_2d_out_we0);
    buf_2d_out_U->d0(grp_dct_2d_fu_190_out_block_d0);
    buf_2d_out_U->q0(buf_2d_out_q0);
    grp_dct_2d_fu_190 = new dct_2d("grp_dct_2d_fu_190");
    grp_dct_2d_fu_190->ap_clk(ap_clk);
    grp_dct_2d_fu_190->ap_rst(ap_rst);
    grp_dct_2d_fu_190->ap_start(grp_dct_2d_fu_190_ap_start);
    grp_dct_2d_fu_190->ap_done(grp_dct_2d_fu_190_ap_done);
    grp_dct_2d_fu_190->ap_idle(grp_dct_2d_fu_190_ap_idle);
    grp_dct_2d_fu_190->ap_ready(grp_dct_2d_fu_190_ap_ready);
    grp_dct_2d_fu_190->in_block_address0(grp_dct_2d_fu_190_in_block_address0);
    grp_dct_2d_fu_190->in_block_ce0(grp_dct_2d_fu_190_in_block_ce0);
    grp_dct_2d_fu_190->in_block_q0(buf_2d_in_q0);
    grp_dct_2d_fu_190->out_block_address0(grp_dct_2d_fu_190_out_block_address0);
    grp_dct_2d_fu_190->out_block_ce0(grp_dct_2d_fu_190_out_block_ce0);
    grp_dct_2d_fu_190->out_block_we0(grp_dct_2d_fu_190_out_block_we0);
    grp_dct_2d_fu_190->out_block_d0(grp_dct_2d_fu_190_out_block_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln59_fu_204_p2);
    sensitive << ( indvar_flatten_reg_124 );

    SC_METHOD(thread_add_ln62_1_fu_285_p2);
    sensitive << ( zext_ln61_1_fu_278_p1 );
    sensitive << ( zext_ln62_1_fu_282_p1 );

    SC_METHOD(thread_add_ln62_fu_254_p2);
    sensitive << ( zext_ln61_fu_250_p1 );
    sensitive << ( shl_ln62_mid2_fu_242_p3 );

    SC_METHOD(thread_add_ln71_fu_302_p2);
    sensitive << ( indvar_flatten11_reg_157 );

    SC_METHOD(thread_add_ln74_1_fu_368_p2);
    sensitive << ( zext_ln71_fu_344_p1 );
    sensitive << ( zext_ln74_fu_364_p1 );

    SC_METHOD(thread_add_ln74_fu_379_p2);
    sensitive << ( zext_ln73_fu_360_p1 );
    sensitive << ( shl_ln74_mid2_fu_352_p3 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state7_pp1_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln59_fu_198_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state6);
    sensitive << ( icmp_ln71_fu_296_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_phi_mux_r_0_i2_phi_fu_172_p4);
    sensitive << ( r_0_i2_reg_168 );
    sensitive << ( icmp_ln71_reg_425 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( select_ln71_1_reg_434 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_phi_mux_r_0_i_phi_fu_139_p4);
    sensitive << ( r_0_i_reg_135 );
    sensitive << ( icmp_ln59_reg_395 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln59_1_reg_409 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_buf_2d_in_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_in_block_address0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln62_2_fu_291_p1 );

    SC_METHOD(thread_buf_2d_in_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_in_block_ce0 );

    SC_METHOD(thread_buf_2d_in_we0);
    sensitive << ( icmp_ln59_reg_395 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_buf_2d_out_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_out_block_address0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln74_1_fu_374_p1 );

    SC_METHOD(thread_buf_2d_out_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_out_block_ce0 );

    SC_METHOD(thread_buf_2d_out_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_out_block_we0 );

    SC_METHOD(thread_c_1_fu_385_p2);
    sensitive << ( select_ln71_fu_320_p3 );

    SC_METHOD(thread_c_fu_265_p2);
    sensitive << ( select_ln59_fu_222_p3 );

    SC_METHOD(thread_grp_dct_2d_fu_190_ap_start);
    sensitive << ( grp_dct_2d_fu_190_ap_start_reg );

    SC_METHOD(thread_icmp_ln59_fu_198_p2);
    sensitive << ( indvar_flatten_reg_124 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln61_fu_216_p2);
    sensitive << ( c_0_i_reg_146 );
    sensitive << ( icmp_ln59_fu_198_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln71_fu_296_p2);
    sensitive << ( indvar_flatten11_reg_157 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln73_fu_314_p2);
    sensitive << ( c_0_i4_reg_179 );
    sensitive << ( icmp_ln71_fu_296_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln62_fu_260_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln74_2_fu_391_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( buf_2d_out_q0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( icmp_ln71_reg_425 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_r_1_fu_308_p2);
    sensitive << ( ap_phi_mux_r_0_i2_phi_fu_172_p4 );

    SC_METHOD(thread_r_fu_210_p2);
    sensitive << ( ap_phi_mux_r_0_i_phi_fu_139_p4 );

    SC_METHOD(thread_select_ln59_1_fu_230_p3);
    sensitive << ( ap_phi_mux_r_0_i_phi_fu_139_p4 );
    sensitive << ( icmp_ln61_fu_216_p2 );
    sensitive << ( r_fu_210_p2 );

    SC_METHOD(thread_select_ln59_fu_222_p3);
    sensitive << ( c_0_i_reg_146 );
    sensitive << ( icmp_ln61_fu_216_p2 );

    SC_METHOD(thread_select_ln71_1_fu_328_p3);
    sensitive << ( ap_phi_mux_r_0_i2_phi_fu_172_p4 );
    sensitive << ( icmp_ln73_fu_314_p2 );
    sensitive << ( r_1_fu_308_p2 );

    SC_METHOD(thread_select_ln71_fu_320_p3);
    sensitive << ( c_0_i4_reg_179 );
    sensitive << ( icmp_ln73_fu_314_p2 );

    SC_METHOD(thread_shl_ln62_mid2_fu_242_p3);
    sensitive << ( trunc_ln59_fu_238_p1 );

    SC_METHOD(thread_shl_ln74_mid2_fu_352_p3);
    sensitive << ( trunc_ln71_fu_348_p1 );

    SC_METHOD(thread_tmp_9_fu_271_p3);
    sensitive << ( select_ln59_1_reg_409 );

    SC_METHOD(thread_tmp_s_fu_336_p3);
    sensitive << ( select_ln71_1_fu_328_p3 );

    SC_METHOD(thread_trunc_ln59_fu_238_p1);
    sensitive << ( select_ln59_1_fu_230_p3 );

    SC_METHOD(thread_trunc_ln71_fu_348_p1);
    sensitive << ( select_ln71_1_fu_328_p3 );

    SC_METHOD(thread_zext_ln61_1_fu_278_p1);
    sensitive << ( tmp_9_fu_271_p3 );

    SC_METHOD(thread_zext_ln61_fu_250_p1);
    sensitive << ( select_ln59_fu_222_p3 );

    SC_METHOD(thread_zext_ln62_1_fu_282_p1);
    sensitive << ( select_ln59_reg_404 );

    SC_METHOD(thread_zext_ln62_2_fu_291_p1);
    sensitive << ( add_ln62_1_fu_285_p2 );

    SC_METHOD(thread_zext_ln62_fu_260_p1);
    sensitive << ( add_ln62_fu_254_p2 );

    SC_METHOD(thread_zext_ln71_fu_344_p1);
    sensitive << ( tmp_s_fu_336_p3 );

    SC_METHOD(thread_zext_ln73_fu_360_p1);
    sensitive << ( select_ln71_fu_320_p3 );

    SC_METHOD(thread_zext_ln74_1_fu_374_p1);
    sensitive << ( add_ln74_1_fu_368_p2 );

    SC_METHOD(thread_zext_ln74_2_fu_391_p1);
    sensitive << ( add_ln74_reg_444 );

    SC_METHOD(thread_zext_ln74_fu_364_p1);
    sensitive << ( select_ln71_fu_320_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln59_fu_198_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln71_fu_296_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_dct_2d_fu_190_ap_done );
    sensitive << ( ap_block_pp1_stage0_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    grp_dct_2d_fu_190_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_124, "indvar_flatten_reg_124");
    sc_trace(mVcdFile, r_0_i_reg_135, "r_0_i_reg_135");
    sc_trace(mVcdFile, c_0_i_reg_146, "c_0_i_reg_146");
    sc_trace(mVcdFile, indvar_flatten11_reg_157, "indvar_flatten11_reg_157");
    sc_trace(mVcdFile, r_0_i2_reg_168, "r_0_i2_reg_168");
    sc_trace(mVcdFile, c_0_i4_reg_179, "c_0_i4_reg_179");
    sc_trace(mVcdFile, icmp_ln59_fu_198_p2, "icmp_ln59_fu_198_p2");
    sc_trace(mVcdFile, icmp_ln59_reg_395, "icmp_ln59_reg_395");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln59_fu_204_p2, "add_ln59_fu_204_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln59_fu_222_p3, "select_ln59_fu_222_p3");
    sc_trace(mVcdFile, select_ln59_reg_404, "select_ln59_reg_404");
    sc_trace(mVcdFile, select_ln59_1_fu_230_p3, "select_ln59_1_fu_230_p3");
    sc_trace(mVcdFile, select_ln59_1_reg_409, "select_ln59_1_reg_409");
    sc_trace(mVcdFile, c_fu_265_p2, "c_fu_265_p2");
    sc_trace(mVcdFile, icmp_ln71_fu_296_p2, "icmp_ln71_fu_296_p2");
    sc_trace(mVcdFile, icmp_ln71_reg_425, "icmp_ln71_reg_425");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter0, "ap_block_state6_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp1_stage0_iter1, "ap_block_state7_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, add_ln71_fu_302_p2, "add_ln71_fu_302_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, select_ln71_1_fu_328_p3, "select_ln71_1_fu_328_p3");
    sc_trace(mVcdFile, select_ln71_1_reg_434, "select_ln71_1_reg_434");
    sc_trace(mVcdFile, add_ln74_fu_379_p2, "add_ln74_fu_379_p2");
    sc_trace(mVcdFile, add_ln74_reg_444, "add_ln74_reg_444");
    sc_trace(mVcdFile, c_1_fu_385_p2, "c_1_fu_385_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_ap_ready, "grp_dct_2d_fu_190_ap_ready");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_ap_done, "grp_dct_2d_fu_190_ap_done");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state6, "ap_condition_pp1_exit_iter0_state6");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, buf_2d_in_address0, "buf_2d_in_address0");
    sc_trace(mVcdFile, buf_2d_in_ce0, "buf_2d_in_ce0");
    sc_trace(mVcdFile, buf_2d_in_we0, "buf_2d_in_we0");
    sc_trace(mVcdFile, buf_2d_in_q0, "buf_2d_in_q0");
    sc_trace(mVcdFile, buf_2d_out_address0, "buf_2d_out_address0");
    sc_trace(mVcdFile, buf_2d_out_ce0, "buf_2d_out_ce0");
    sc_trace(mVcdFile, buf_2d_out_we0, "buf_2d_out_we0");
    sc_trace(mVcdFile, buf_2d_out_q0, "buf_2d_out_q0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_ap_start, "grp_dct_2d_fu_190_ap_start");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_ap_idle, "grp_dct_2d_fu_190_ap_idle");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_in_block_address0, "grp_dct_2d_fu_190_in_block_address0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_in_block_ce0, "grp_dct_2d_fu_190_in_block_ce0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_out_block_address0, "grp_dct_2d_fu_190_out_block_address0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_out_block_ce0, "grp_dct_2d_fu_190_out_block_ce0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_out_block_we0, "grp_dct_2d_fu_190_out_block_we0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_out_block_d0, "grp_dct_2d_fu_190_out_block_d0");
    sc_trace(mVcdFile, ap_phi_mux_r_0_i_phi_fu_139_p4, "ap_phi_mux_r_0_i_phi_fu_139_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_r_0_i2_phi_fu_172_p4, "ap_phi_mux_r_0_i2_phi_fu_172_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, grp_dct_2d_fu_190_ap_start_reg, "grp_dct_2d_fu_190_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln62_fu_260_p1, "zext_ln62_fu_260_p1");
    sc_trace(mVcdFile, zext_ln62_2_fu_291_p1, "zext_ln62_2_fu_291_p1");
    sc_trace(mVcdFile, zext_ln74_1_fu_374_p1, "zext_ln74_1_fu_374_p1");
    sc_trace(mVcdFile, zext_ln74_2_fu_391_p1, "zext_ln74_2_fu_391_p1");
    sc_trace(mVcdFile, icmp_ln61_fu_216_p2, "icmp_ln61_fu_216_p2");
    sc_trace(mVcdFile, r_fu_210_p2, "r_fu_210_p2");
    sc_trace(mVcdFile, trunc_ln59_fu_238_p1, "trunc_ln59_fu_238_p1");
    sc_trace(mVcdFile, zext_ln61_fu_250_p1, "zext_ln61_fu_250_p1");
    sc_trace(mVcdFile, shl_ln62_mid2_fu_242_p3, "shl_ln62_mid2_fu_242_p3");
    sc_trace(mVcdFile, add_ln62_fu_254_p2, "add_ln62_fu_254_p2");
    sc_trace(mVcdFile, tmp_9_fu_271_p3, "tmp_9_fu_271_p3");
    sc_trace(mVcdFile, zext_ln61_1_fu_278_p1, "zext_ln61_1_fu_278_p1");
    sc_trace(mVcdFile, zext_ln62_1_fu_282_p1, "zext_ln62_1_fu_282_p1");
    sc_trace(mVcdFile, add_ln62_1_fu_285_p2, "add_ln62_1_fu_285_p2");
    sc_trace(mVcdFile, icmp_ln73_fu_314_p2, "icmp_ln73_fu_314_p2");
    sc_trace(mVcdFile, r_1_fu_308_p2, "r_1_fu_308_p2");
    sc_trace(mVcdFile, tmp_s_fu_336_p3, "tmp_s_fu_336_p3");
    sc_trace(mVcdFile, trunc_ln71_fu_348_p1, "trunc_ln71_fu_348_p1");
    sc_trace(mVcdFile, select_ln71_fu_320_p3, "select_ln71_fu_320_p3");
    sc_trace(mVcdFile, zext_ln71_fu_344_p1, "zext_ln71_fu_344_p1");
    sc_trace(mVcdFile, zext_ln74_fu_364_p1, "zext_ln74_fu_364_p1");
    sc_trace(mVcdFile, add_ln74_1_fu_368_p2, "add_ln74_1_fu_368_p2");
    sc_trace(mVcdFile, zext_ln73_fu_360_p1, "zext_ln73_fu_360_p1");
    sc_trace(mVcdFile, shl_ln74_mid2_fu_352_p3, "shl_ln74_mid2_fu_352_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
    mHdltvinHandle.open("dct.hdltvin.dat");
    mHdltvoutHandle.open("dct.hdltvout.dat");
}

dct::~dct() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete buf_2d_in_U;
    delete buf_2d_out_U;
    delete grp_dct_2d_fu_190;
}

void dct::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state6.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                    esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state6.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state6.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                    esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_296_p2.read()))) {
        c_0_i4_reg_179 = c_1_fu_385_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
        c_0_i4_reg_179 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_0))) {
        c_0_i_reg_146 = c_fu_265_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_0_i_reg_146 = ap_const_lv4_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_dct_2d_fu_190_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            grp_dct_2d_fu_190_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dct_2d_fu_190_ap_ready.read())) {
            grp_dct_2d_fu_190_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_296_p2.read()))) {
        indvar_flatten11_reg_157 = add_ln71_fu_302_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
        indvar_flatten11_reg_157 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_124 = add_ln59_fu_204_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_124 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_425.read()))) {
        r_0_i2_reg_168 = select_ln71_1_reg_434.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
        r_0_i2_reg_168 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_reg_395.read(), ap_const_lv1_0))) {
        r_0_i_reg_135 = select_ln59_1_reg_409.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_i_reg_135 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_296_p2.read()))) {
        add_ln74_reg_444 = add_ln74_fu_379_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln59_reg_395 = icmp_ln59_fu_198_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln71_reg_425 = icmp_ln71_fu_296_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_0))) {
        select_ln59_1_reg_409 = select_ln59_1_fu_230_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_0))) {
        select_ln59_reg_404 = select_ln59_fu_222_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_296_p2.read()))) {
        select_ln71_1_reg_434 = select_ln71_1_fu_328_p3.read();
    }
}

void dct::thread_add_ln59_fu_204_p2() {
    add_ln59_fu_204_p2 = (!indvar_flatten_reg_124.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_reg_124.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct::thread_add_ln62_1_fu_285_p2() {
    add_ln62_1_fu_285_p2 = (!zext_ln61_1_fu_278_p1.read().is_01() || !zext_ln62_1_fu_282_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln61_1_fu_278_p1.read()) + sc_biguint<8>(zext_ln62_1_fu_282_p1.read()));
}

void dct::thread_add_ln62_fu_254_p2() {
    add_ln62_fu_254_p2 = (!zext_ln61_fu_250_p1.read().is_01() || !shl_ln62_mid2_fu_242_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln61_fu_250_p1.read()) + sc_biguint<6>(shl_ln62_mid2_fu_242_p3.read()));
}

void dct::thread_add_ln71_fu_302_p2() {
    add_ln71_fu_302_p2 = (!indvar_flatten11_reg_157.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten11_reg_157.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct::thread_add_ln74_1_fu_368_p2() {
    add_ln74_1_fu_368_p2 = (!zext_ln71_fu_344_p1.read().is_01() || !zext_ln74_fu_364_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln71_fu_344_p1.read()) + sc_biguint<8>(zext_ln74_fu_364_p1.read()));
}

void dct::thread_add_ln74_fu_379_p2() {
    add_ln74_fu_379_p2 = (!zext_ln73_fu_360_p1.read().is_01() || !shl_ln74_mid2_fu_352_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln73_fu_360_p1.read()) + sc_biguint<6>(shl_ln74_mid2_fu_352_p3.read()));
}

void dct::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dct::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void dct::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dct::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void dct::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void dct::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void dct::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_state6_pp1_stage0_iter0() {
    ap_block_state6_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_block_state7_pp1_stage0_iter1() {
    ap_block_state7_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dct::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dct::thread_ap_condition_pp1_exit_iter0_state6() {
    if (esl_seteq<1,1,1>(icmp_ln71_fu_296_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state6 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state6 = ap_const_logic_0;
    }
}

void dct::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dct::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void dct::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dct::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void dct::thread_ap_phi_mux_r_0_i2_phi_fu_172_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_425.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_r_0_i2_phi_fu_172_p4 = select_ln71_1_reg_434.read();
    } else {
        ap_phi_mux_r_0_i2_phi_fu_172_p4 = r_0_i2_reg_168.read();
    }
}

void dct::thread_ap_phi_mux_r_0_i_phi_fu_139_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_reg_395.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_r_0_i_phi_fu_139_p4 = select_ln59_1_reg_409.read();
    } else {
        ap_phi_mux_r_0_i_phi_fu_139_p4 = r_0_i_reg_135.read();
    }
}

void dct::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct::thread_buf_2d_in_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        buf_2d_in_address0 =  (sc_lv<6>) (zext_ln62_2_fu_291_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_in_address0 = grp_dct_2d_fu_190_in_block_address0.read();
    } else {
        buf_2d_in_address0 = "XXXXXX";
    }
}

void dct::thread_buf_2d_in_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        buf_2d_in_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_in_ce0 = grp_dct_2d_fu_190_in_block_ce0.read();
    } else {
        buf_2d_in_ce0 = ap_const_logic_0;
    }
}

void dct::thread_buf_2d_in_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_reg_395.read(), ap_const_lv1_0))) {
        buf_2d_in_we0 = ap_const_logic_1;
    } else {
        buf_2d_in_we0 = ap_const_logic_0;
    }
}

void dct::thread_buf_2d_out_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        buf_2d_out_address0 =  (sc_lv<6>) (zext_ln74_1_fu_374_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_out_address0 = grp_dct_2d_fu_190_out_block_address0.read();
    } else {
        buf_2d_out_address0 = "XXXXXX";
    }
}

void dct::thread_buf_2d_out_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        buf_2d_out_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_out_ce0 = grp_dct_2d_fu_190_out_block_ce0.read();
    } else {
        buf_2d_out_ce0 = ap_const_logic_0;
    }
}

void dct::thread_buf_2d_out_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_2d_out_we0 = grp_dct_2d_fu_190_out_block_we0.read();
    } else {
        buf_2d_out_we0 = ap_const_logic_0;
    }
}

void dct::thread_c_1_fu_385_p2() {
    c_1_fu_385_p2 = (!ap_const_lv4_1.is_01() || !select_ln71_fu_320_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln71_fu_320_p3.read()));
}

void dct::thread_c_fu_265_p2() {
    c_fu_265_p2 = (!ap_const_lv4_1.is_01() || !select_ln59_fu_222_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln59_fu_222_p3.read()));
}

void dct::thread_grp_dct_2d_fu_190_ap_start() {
    grp_dct_2d_fu_190_ap_start = grp_dct_2d_fu_190_ap_start_reg.read();
}

void dct::thread_icmp_ln59_fu_198_p2() {
    icmp_ln59_fu_198_p2 = (!indvar_flatten_reg_124.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_124.read() == ap_const_lv7_40);
}

void dct::thread_icmp_ln61_fu_216_p2() {
    icmp_ln61_fu_216_p2 = (!c_0_i_reg_146.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(c_0_i_reg_146.read() == ap_const_lv4_8);
}

void dct::thread_icmp_ln71_fu_296_p2() {
    icmp_ln71_fu_296_p2 = (!indvar_flatten11_reg_157.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten11_reg_157.read() == ap_const_lv7_40);
}

void dct::thread_icmp_ln73_fu_314_p2() {
    icmp_ln73_fu_314_p2 = (!c_0_i4_reg_179.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(c_0_i4_reg_179.read() == ap_const_lv4_8);
}

void dct::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<6>) (zext_ln62_fu_260_p1.read());
}

void dct::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void dct::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<6>) (zext_ln74_2_fu_391_p1.read());
}

void dct::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void dct::thread_output_r_d0() {
    output_r_d0 = buf_2d_out_q0.read();
}

void dct::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_reg_425.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void dct::thread_r_1_fu_308_p2() {
    r_1_fu_308_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_r_0_i2_phi_fu_172_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_r_0_i2_phi_fu_172_p4.read()));
}

void dct::thread_r_fu_210_p2() {
    r_fu_210_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_r_0_i_phi_fu_139_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_r_0_i_phi_fu_139_p4.read()));
}

void dct::thread_select_ln59_1_fu_230_p3() {
    select_ln59_1_fu_230_p3 = (!icmp_ln61_fu_216_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln61_fu_216_p2.read()[0].to_bool())? r_fu_210_p2.read(): ap_phi_mux_r_0_i_phi_fu_139_p4.read());
}

void dct::thread_select_ln59_fu_222_p3() {
    select_ln59_fu_222_p3 = (!icmp_ln61_fu_216_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln61_fu_216_p2.read()[0].to_bool())? ap_const_lv4_0: c_0_i_reg_146.read());
}

void dct::thread_select_ln71_1_fu_328_p3() {
    select_ln71_1_fu_328_p3 = (!icmp_ln73_fu_314_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln73_fu_314_p2.read()[0].to_bool())? r_1_fu_308_p2.read(): ap_phi_mux_r_0_i2_phi_fu_172_p4.read());
}

void dct::thread_select_ln71_fu_320_p3() {
    select_ln71_fu_320_p3 = (!icmp_ln73_fu_314_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln73_fu_314_p2.read()[0].to_bool())? ap_const_lv4_0: c_0_i4_reg_179.read());
}

void dct::thread_shl_ln62_mid2_fu_242_p3() {
    shl_ln62_mid2_fu_242_p3 = esl_concat<3,3>(trunc_ln59_fu_238_p1.read(), ap_const_lv3_0);
}

void dct::thread_shl_ln74_mid2_fu_352_p3() {
    shl_ln74_mid2_fu_352_p3 = esl_concat<3,3>(trunc_ln71_fu_348_p1.read(), ap_const_lv3_0);
}

void dct::thread_tmp_9_fu_271_p3() {
    tmp_9_fu_271_p3 = esl_concat<4,3>(select_ln59_1_reg_409.read(), ap_const_lv3_0);
}

void dct::thread_tmp_s_fu_336_p3() {
    tmp_s_fu_336_p3 = esl_concat<4,3>(select_ln71_1_fu_328_p3.read(), ap_const_lv3_0);
}

void dct::thread_trunc_ln59_fu_238_p1() {
    trunc_ln59_fu_238_p1 = select_ln59_1_fu_230_p3.read().range(3-1, 0);
}

void dct::thread_trunc_ln71_fu_348_p1() {
    trunc_ln71_fu_348_p1 = select_ln71_1_fu_328_p3.read().range(3-1, 0);
}

void dct::thread_zext_ln61_1_fu_278_p1() {
    zext_ln61_1_fu_278_p1 = esl_zext<8,7>(tmp_9_fu_271_p3.read());
}

void dct::thread_zext_ln61_fu_250_p1() {
    zext_ln61_fu_250_p1 = esl_zext<6,4>(select_ln59_fu_222_p3.read());
}

void dct::thread_zext_ln62_1_fu_282_p1() {
    zext_ln62_1_fu_282_p1 = esl_zext<8,4>(select_ln59_reg_404.read());
}

void dct::thread_zext_ln62_2_fu_291_p1() {
    zext_ln62_2_fu_291_p1 = esl_zext<64,8>(add_ln62_1_fu_285_p2.read());
}

void dct::thread_zext_ln62_fu_260_p1() {
    zext_ln62_fu_260_p1 = esl_zext<64,6>(add_ln62_fu_254_p2.read());
}

void dct::thread_zext_ln71_fu_344_p1() {
    zext_ln71_fu_344_p1 = esl_zext<8,7>(tmp_s_fu_336_p3.read());
}

void dct::thread_zext_ln73_fu_360_p1() {
    zext_ln73_fu_360_p1 = esl_zext<6,4>(select_ln71_fu_320_p3.read());
}

void dct::thread_zext_ln74_1_fu_374_p1() {
    zext_ln74_1_fu_374_p1 = esl_zext<64,8>(add_ln74_1_fu_368_p2.read());
}

void dct::thread_zext_ln74_2_fu_391_p1() {
    zext_ln74_2_fu_391_p1 = esl_zext<64,6>(add_ln74_reg_444.read());
}

void dct::thread_zext_ln74_fu_364_p1() {
    zext_ln74_fu_364_p1 = esl_zext<8,4>(select_ln71_fu_320_p3.read());
}

void dct::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln59_fu_198_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(grp_dct_2d_fu_190_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln71_fu_296_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln71_fu_296_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

void dct::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

